### ISSUE TITLE
"New Task" button does not seem to do anything after creating a new project

### ISSUE THREAD

**Issue by skylersidner** [StevenThiesfeld/taskmaster#2]
Neat button effects!  But after I created a new project ("ThisOlProject"), I couldn't seem to go anywhere from there.

**Comment by beth-str** [comment]
Same for me.

**Comment by StevenThiesfeld** [comment]
Thanks for finding that, apparently either a method name or column name I had is a reserved word for heroku so that bug didn't show up in development, fixed.
