### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Derek68038** [StevenThiesfeld/taskmaster#3]
Hey Steven, nice job on your Taskmaster project!  I just wanted to give you a quick feedback on something I encountered while using the app. When I created my first task, it showed up in my profile as task #2 rather than #1. I created a second one and it was showing as #3. So for some reason it didn't start off with #1. I wasn't sure if it was something I may of done while messing around on the site, but just thought it was worth passing along to you. Ok, that's all I've got!

Derek

**Comment by StevenThiesfeld** [comment]
Interesting, thanks for the feedback.  I'll take a look at it.

**Comment by StevenThiesfeld** [comment]
Issue resolved, there might be some strangeness in old tasks having duplicate numbers, but all new tasks should be working fine.
